//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SharpServer.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class FtpReplies {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FtpReplies() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SharpServer.Localization.FtpReplies", typeof(FtpReplies).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; is the current directory.
        /// </summary>
        internal static string CURRENT_DIRECTORY {
            get {
                return ResourceManager.GetString("CURRENT_DIRECTORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory already exists.
        /// </summary>
        internal static string DIRECTORY_EXISTS {
            get {
                return ResourceManager.GetString("DIRECTORY_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory not found.
        /// </summary>
        internal static string DIRECTORY_NOT_FOUND {
            get {
                return ResourceManager.GetString("DIRECTORY_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabling TLS Connection.
        /// </summary>
        internal static string ENABLING_TLS {
            get {
                return ResourceManager.GetString("ENABLING_TLS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entering Extended Passive Mode (|||{0}|).
        /// </summary>
        internal static string ENTERING_EXTENDED_PASSIVE_MODE {
            get {
                return ResourceManager.GetString("ENTERING_EXTENDED_PASSIVE_MODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entering Passive Mode ({0},{1},{2},{3},{4},{5}).
        /// </summary>
        internal static string ENTERING_PASSIVE_MODE {
            get {
                return ResourceManager.GetString("ENTERING_PASSIVE_MODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extensions supported.
        /// </summary>
        internal static string EXTENSIONS_SUPPORTED {
            get {
                return ResourceManager.GetString("EXTENSIONS_SUPPORTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requested file action okay, completed.
        /// </summary>
        internal static string FILE_ACTION_COMPLETE {
            get {
                return ResourceManager.GetString("FILE_ACTION_COMPLETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requested file action not taken.
        /// </summary>
        internal static string FILE_ACTION_NOT_TAKEN {
            get {
                return ResourceManager.GetString("FILE_ACTION_NOT_TAKEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File not found.
        /// </summary>
        internal static string FILE_NOT_FOUND {
            get {
                return ResourceManager.GetString("FILE_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User logged in.
        /// </summary>
        internal static string LOGGED_IN {
            get {
                return ResourceManager.GetString("LOGGED_IN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Need Two Factor Code.
        /// </summary>
        internal static string NEED_TWO_FACTOR_CODE {
            get {
                return ResourceManager.GetString("NEED_TWO_FACTOR_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command not implemented.
        /// </summary>
        internal static string NOT_IMPLEMENTED {
            get {
                return ResourceManager.GetString("NOT_IMPLEMENTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command not implemented for that parameter.
        /// </summary>
        internal static string NOT_IMPLEMENTED_FOR_PARAMETER {
            get {
                return ResourceManager.GetString("NOT_IMPLEMENTED_FOR_PARAMETER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not logged in.
        /// </summary>
        internal static string NOT_LOGGED_IN {
            get {
                return ResourceManager.GetString("NOT_LOGGED_IN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opening {0} mode data transfer for {1}.
        /// </summary>
        internal static string OPENING_DATA_TRANSFER {
            get {
                return ResourceManager.GetString("OPENING_DATA_TRANSFER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter {0} not recogonized.
        /// </summary>
        internal static string PARAMETER_NOT_RECOGNIZED {
            get {
                return ResourceManager.GetString("PARAMETER_NOT_RECOGNIZED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service closing control connection.
        /// </summary>
        internal static string QUIT {
            get {
                return ResourceManager.GetString("QUIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requested file action pending further information.
        /// </summary>
        internal static string RENAME_FROM {
            get {
                return ResourceManager.GetString("RENAME_FROM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service ready for new user.
        /// </summary>
        internal static string SERVICE_READY {
            get {
                return ResourceManager.GetString("SERVICE_READY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UNIX Type: L8.
        /// </summary>
        internal static string SYSTEM {
            get {
                return ResourceManager.GetString("SYSTEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer aborted.
        /// </summary>
        internal static string TRANSFER_ABORTED {
            get {
                return ResourceManager.GetString("TRANSFER_ABORTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closing data connection, transfer successful.
        /// </summary>
        internal static string TRANSFER_SUCCESSFUL {
            get {
                return ResourceManager.GetString("TRANSFER_SUCCESSFUL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to open data connection.
        /// </summary>
        internal static string UNABLE_TO_OPEN_DATA_CONNECTION {
            get {
                return ResourceManager.GetString("UNABLE_TO_OPEN_DATA_CONNECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username ok, need password.
        /// </summary>
        internal static string USER_OK {
            get {
                return ResourceManager.GetString("USER_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UTF8 Encoding turned on.
        /// </summary>
        internal static string UTF8_ENCODING_ON {
            get {
                return ResourceManager.GetString("UTF8_ENCODING_ON", resourceCulture);
            }
        }
    }
}
